server:
  port: 8607
spring:
  # 数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/geek?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    password: 123456

# mybatis-plus
mybatis-plus:
  mapper-locations: classpath*:cn/lico/geek/modules/**/xml/*.xml
logging:
  level:
    cn:
      meteor:
        beyondclouds: debug
    com:
      corundumstudio: info