server:
  port: 8607
spring:
  # 数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.113.197.253:3306/yunwai?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    password: 123456

  # elasticsearch
  data:
    elasticsearch:
      repositories:
        enabled: false
  elasticsearch:
    rest:
      uris: http://47.113.197.253:9200

  # kafka
  kafka:
    bootstrap-servers: 47.113.197.253:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: beyond-clouds
      enable-auto-commit: true
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    listener:
      missing-topics-fatal: false
  #reids
  redis:
    host: 47.113.197.253
    port: 6379

# mybatis-plus
mybatis-plus:
  mapper-locations: classpath*:cn/lico/geek/modules/**/xml/*.xml
logging:
  level:
    cn:
      meteor:
        beyondclouds: debug
    com:
      corundumstudio: info

#七牛云配置
oss:
  accessKey: JHNbeGgqjKENX-mWDHpXu5CBuiXmMW8YHSNuC-cq
  secretKey: tbUM1edpmMGrcThk3JH3TksOUcJm74CARNQZBvrv
  bucket: yunwaicunchu

geek:
  kafka:
    topics:
      data-item-change: topic.beyondclouds.dataitem.change


